/**
 * Dados mock de unidades monitoradas
 *
 * Usado enquanto a integração com a API Sinapse não está pronta.
 */
import type { Unidade } from '../composables/types'

export const MOCK_UNIDADES: Unidade[] = [
  {
    placeId: 'ubs-001',
    titulo: 'UBS Vila Mariana',
    tipoUnidade: 'ubs',
    endereco: 'Rua Domingos de Morais, 2187',
    bairro: 'Vila Mariana',
    cidade: 'São Paulo',
    estado: 'SP',
    regiao: 'SE',
    latitude: -23.5895,
    longitude: -46.6388,
    ativa: true,
    tempoReal: 1,
    notaTotal: 4.2,
    totalAvaliacoes: 156
  },
  {
    placeId: 'upa-001',
    titulo: 'UPA Campo Limpo',
    tipoUnidade: 'upa',
    endereco: 'Estrada do Campo Limpo, 459',
    bairro: 'Campo Limpo',
    cidade: 'São Paulo',
    estado: 'SP',
    regiao: 'SE',
    latitude: -23.6472,
    longitude: -46.7585,
    ativa: true,
    tempoReal: 1,
    notaTotal: 3.8,
    totalAvaliacoes: 89
  },
  {
    placeId: 'drog-001',
    titulo: 'Drogaria São Paulo - Pinheiros',
    tipoUnidade: 'drogarias',
    endereco: 'Rua dos Pinheiros, 1020',
    bairro: 'Pinheiros',
    cidade: 'São Paulo',
    estado: 'SP',
    regiao: 'SE',
    latitude: -23.5631,
    longitude: -46.6919,
    ativa: true,
    tempoReal: 2,
    notaTotal: 4.5,
    totalAvaliacoes: 230
  },
  {
    placeId: 'ubs-002',
    titulo: 'UBS Copacabana',
    tipoUnidade: 'ubs',
    endereco: 'Rua Siqueira Campos, 93',
    bairro: 'Copacabana',
    cidade: 'Rio de Janeiro',
    estado: 'RJ',
    regiao: 'SE',
    latitude: -22.9662,
    longitude: -43.1868,
    ativa: true,
    tempoReal: 1,
    notaTotal: 3.9,
    totalAvaliacoes: 112
  },
  {
    placeId: 'upa-002',
    titulo: 'UPA Marechal Hermes',
    tipoUnidade: 'upa',
    endereco: 'Av. Marechal Fontenelle, 3400',
    bairro: 'Marechal Hermes',
    cidade: 'Rio de Janeiro',
    estado: 'RJ',
    regiao: 'SE',
    latitude: -22.8564,
    longitude: -43.3697,
    ativa: true,
    tempoReal: 0,
    notaTotal: 3.2,
    totalAvaliacoes: 67
  },
  {
    placeId: 'drog-002',
    titulo: 'Drogasil - Asa Sul',
    tipoUnidade: 'drogarias',
    endereco: 'SCS Quadra 4, Bloco A',
    bairro: 'Asa Sul',
    cidade: 'Brasília',
    estado: 'DF',
    regiao: 'CO',
    latitude: -15.7942,
    longitude: -47.8825,
    ativa: true,
    tempoReal: 2,
    notaTotal: 4.7,
    totalAvaliacoes: 310
  },
  {
    placeId: 'ubs-003',
    titulo: 'UBS Boa Viagem',
    tipoUnidade: 'ubs',
    endereco: 'Rua Barão de Souza Leão, 264',
    bairro: 'Boa Viagem',
    cidade: 'Recife',
    estado: 'PE',
    regiao: 'NE',
    latitude: -8.1192,
    longitude: -34.9015,
    ativa: true,
    tempoReal: 1,
    notaTotal: 3.5,
    totalAvaliacoes: 78
  },
  {
    placeId: 'upa-003',
    titulo: 'UPA Manaíra',
    tipoUnidade: 'upa',
    endereco: 'Av. Gov. Flávio Ribeiro Coutinho, 805',
    bairro: 'Manaíra',
    cidade: 'João Pessoa',
    estado: 'PB',
    regiao: 'NE',
    latitude: -7.1052,
    longitude: -34.8328,
    ativa: false,
    tempoReal: 0,
    notaTotal: 2.9,
    totalAvaliacoes: 45
  },
  {
    placeId: 'pet-001',
    titulo: 'Pet Shop Bicho Bom',
    tipoUnidade: 'pet_shop',
    endereco: 'Rua Augusta, 1524',
    bairro: 'Consolação',
    cidade: 'São Paulo',
    estado: 'SP',
    regiao: 'SE',
    latitude: -23.5558,
    longitude: -46.6595,
    ativa: true,
    tempoReal: 0,
    notaTotal: 4.8,
    totalAvaliacoes: 420
  },
  {
    placeId: 'pet-002',
    titulo: 'Clínica Veterinária Vida Animal',
    tipoUnidade: 'pet_atend',
    endereco: 'Rua Oscar Freire, 890',
    bairro: 'Jardins',
    cidade: 'São Paulo',
    estado: 'SP',
    regiao: 'SE',
    latitude: -23.5612,
    longitude: -46.6718,
    ativa: true,
    tempoReal: 1,
    notaTotal: 4.6,
    totalAvaliacoes: 195
  },
  {
    placeId: 'ubs-004',
    titulo: 'UBS Centro - Porto Alegre',
    tipoUnidade: 'ubs',
    endereco: 'Rua Voluntários da Pátria, 320',
    bairro: 'Centro',
    cidade: 'Porto Alegre',
    estado: 'RS',
    regiao: 'S',
    latitude: -30.0277,
    longitude: -51.2287,
    ativa: true,
    tempoReal: 1,
    notaTotal: 4.0,
    totalAvaliacoes: 134
  },
  {
    placeId: 'ubs-005',
    titulo: 'UBS Adrianópolis',
    tipoUnidade: 'ubs',
    endereco: 'Av. Mário Ypiranga, 1580',
    bairro: 'Adrianópolis',
    cidade: 'Manaus',
    estado: 'AM',
    regiao: 'N',
    latitude: -3.1019,
    longitude: -60.025,
    ativa: true,
    tempoReal: 0,
    notaTotal: 3.3,
    totalAvaliacoes: 52
  }
]
